# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'portfolio-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint', '~> 0.44.0'
  pod 'Alamofire', '~> 5.4'
  pod 'ImagePicker'

  # Pods for portfolio-ios

  target 'portfolio-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'portfolio-iosUITests' do
    # Pods for testing
  end

end
